2020-05-28 11:24:17,784 INFO: Team Collab startup [in /home/bibi/bibistuff/team_collab/app/__init__.py:45]
2020-05-28 11:30:35,121 INFO: Team Collab startup [in /home/bibi/bibistuff/team_collab/app/__init__.py:45]
2020-05-28 11:30:45,433 INFO: Team Collab startup [in /home/bibi/bibistuff/team_collab/app/__init__.py:45]
2020-05-28 11:33:09,028 INFO: Team Collab startup [in /home/bibi/bibistuff/team_collab/app/__init__.py:45]
2020-05-28 11:36:24,859 INFO: Team Collab startup [in /home/bibi/bibistuff/team_collab/app/__init__.py:45]
2020-05-28 11:56:54,976 INFO: Team Collab startup [in /home/bibi/bibistuff/team_collab/app/__init__.py:45]
2020-05-28 11:57:22,793 ERROR: Exception on / [GET] [in /home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bibi/bibistuff/team_collab/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bibi/bibistuff/team_collab/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/bibi/bibistuff/team_collab/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/bibi/bibistuff/team_collab/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-28 11:57:52,351 INFO: Team Collab startup [in /home/bibi/bibistuff/team_collab/app/__init__.py:45]
2020-05-28 11:57:58,715 ERROR: Exception on / [GET] [in /home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bibi/bibistuff/team_collab/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bibi/bibistuff/team_collab/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/bibi/bibistuff/team_collab/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/bibi/bibistuff/team_collab/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-28 11:58:03,736 ERROR: Exception on /index [GET] [in /home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bibi/bibistuff/team_collab/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bibi/bibistuff/team_collab/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/bibi/bibistuff/team_collab/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/bibi/bibistuff/team_collab/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/bibi/bibistuff/team_collab/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
